$background = rgb(17171B)
$foreground = rgb(F9F8FC)
$color0 = rgb(3E3E43)
$color1 = rgb(101021)
$color2 = rgb(373769)
$color3 = rgb(514B6B)
$color4 = rgb(757281)
$color5 = rgb(A0B6A7)
$color6 = rgb(B2B0B9)
$color7 = rgb(EEEDF3)
$color8 = rgb(A6A6AA)
$color9 = rgb(15152C)
$color10 = rgb(4A498C)
$color11 = rgb(6C648F)
$color12 = rgb(9C98AC)
$color13 = rgb(D5F3DF)
$color14 = rgb(EDEBF7)
$color15 = rgb(EEEDF3)
