$background = rgb(060004)
$foreground = rgb(F7F4F2)
$color0 = rgb(1D191C)
$color1 = rgb(53404F)
$color2 = rgb(635243)
$color3 = rgb(926E79)
$color4 = rgb(7B826B)
$color5 = rgb(AAA47C)
$color6 = rgb(AFA8A4)
$color7 = rgb(ECE7E5)
$color8 = rgb(A5A2A0)
$color9 = rgb(6F5569)
$color10 = rgb(846D59)
$color11 = rgb(C393A1)
$color12 = rgb(A4AD8F)
$color13 = rgb(E3DAA5)
$color14 = rgb(E9E0DB)
$color15 = rgb(ECE7E5)
