backend = "kmeans"
color_space = "lab"
palette = "dark16"

[templates]
waybar = { template = "waybar.css", target = "~/.cache/wallust/waybar.css" }
kitty  = { template = "kitty.conf", target = "~/.cache/wallust/kitty.conf" }
cava   = { template = "cava.conf", target = "~/.config/cava/config" }
